# .streamlit/secrets.toml
[connections.snowflake]
account = "UAACYYK-AOB68935"
user = "ericvanwinkle"
password = "EatABagof20Dicks!"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
